### ISSUE TITLE
Multi-cradle confusion

### ISSUE THREAD

**Issue by mitchellwrosen** [mpickering/hie-bios#118]
Hi, I'm trying out the multi-cradle support but am running into an issue.

Here's my `hie.yaml` for the https://github.com/unisonweb/unison repo:

```
cradle:
  stack:
    - path: "./parser-typechecker"
      component: "unison-parser-typechecker:lib"
    - path: "./unison-core"
      component: "unison-core:lib"
```

However, opening a file in either of these directories (with cwd = project root where `hie.yaml` is) doesn't seem to work:

```
ghcide-8.6.5: CradleError ExitSuccess ["Multi Cradle: No prefixes matched","pwd: .","filepath/Users/mitchell/haskell/unison","prefixes:","(\"./parser-typechecker\",Stack {component = Just \"unison-parser-typechecker:lib\"})","(\"./unison-core\",Stack {component = Just \"unison-core:lib\"})"]
```

I think it's failing because I don't have a cradle defined for `.`? (But I don't want one... just for the subdirs!)

Any advice would be greatly appreciated. Thanks :)
