### ISSUE TITLE
Convert between stack/cabal naming conventions

### ISSUE THREAD

**Issue by alanz** [mpickering/hie-bios#120]
The hie-bios README gives the following two examples

```yaml
cradle: {stack: {component: "haskell-ide-engine:lib" }}
cradle: {cabal: {component: "lib:haskell-ide-engine"}}
```

They are both referring to the library component in `haskell-ide-engine`, but stack and cabal have different naming conventions for them.

If I have a complex multi-cradle, such as

```yaml
cradle:
  stack:
    - path: "./test/dispatcher/"
      component: "haskell-ide-engine:test:dispatcher-test"
    - path: "./test/functional/"
      component: "haskell-ide-engine:test:func-test"
    - path: "./test/unit/"
      component: "haskell-ide-engine:test:unit-test"
    - path: "./hie-plugin-api/"
      component: "hie-plugin-api:lib"
    - path: "./app/MainHie.hs"
      component: "haskell-ide-engine:exe:hie"
    - path: "./app/HieWrapper.hs"
      component: "haskell-ide-engine:exe:hie-wrapper"
    - path: "./"
      component: "haskell-ide-engine:lib"
```
I would ideally like to just replace `stack` with `cabal` on the second line and have it continue to work.

Can we do some kind of implicit name translation for this case?
