### ISSUE TITLE
Support arguments to bios process

### ISSUE THREAD

**Issue by 3noch** [mpickering/hie-bios#158]
My bios script is just

```bash
#!/usr/bin/env bash
ob internal export-some-stuff > "$HIE_BIOS_OUTPUT"
```

It would be nicer if I could just inline this into `hie.yaml` directly with something like

```yaml
cradle: { bios: { program: 'bash -c "ob internal export-some-stuff > \"$HIE_BIOS_OUTPUT\""' } }
```

**Comment by fendor** [comment]
This ought to work in windows as well, right?
Possible implementation via [shell](https://hackage.haskell.org/package/process-1.6.8.0/docs/System-Process.html#v:shell)

**Comment by jneira** [comment]
I think you could call `cmd` like `bash`

**Comment by fendor** [comment]
Proposed yaml:
```yaml
cradle:
  bios:
    shell: 'bash -c "ob internal export-some-stuff > \"$HIE_BIOS_OUTPUT\""'
```

Maybe we can even ditch the OS dependant part and use just:
```yaml
cradle:
  bios:
    shell: 'ob internal export-some-stuff > \"$HIE_BIOS_OUTPUT\"'
```

**Comment by mpickering** [comment]
Sounds sensible to me.

**Comment by jneira** [comment]
Not sure how can work that for windows and linux, using the same cradle config. One soution could be to have two files `hie,yaml.linux` and `hie.yaml.windows` and uncomment the desired one, but it is not ideal.
It happens too for the `program` case.

What about

```yaml
cradle:
  bios:
    posix:
      shell: 'bash -c "ob internal export-some-stuff > \"$HIE_BIOS_OUTPUT\""'
    windows:
       shell: 'cmd /c "ob internal export-some-stuff > "%HIE_BIOS_OUTPUT%""
```

or 

```yaml
cradle:
  bios:
    posix:
      program: "./hadrian/hie-bios"
    windows:
      program: ".\\hadrian\hie-bios.cmd"
```


> Maybe we can even ditch the OS dependant part and use just:

We will not let the use of other shells like `zsh` in linux or `cmd` vs. `powershell` in windows, no?

**Comment by fendor** [comment]
> We will not let the use of other shells like zsh in linux or cmd vs. powershell in windows, no?

If the user choose to, with `bash -c` etc, then there is no reason against it.

>     cradle:
>       bios:
>         posix:
>           program: "./hadrian/hie-bios"
>         windows:
>           program: ".\\hadrian\\hie-bios.cmd"
 
I kind of dislike the idea. 
It is not a matter of `posix` vs `windows`. It is rather `non-windows` vs `windows`.
I think, the feature we actually think about here is some way of passing conditional flags, in this case conditional on the OS type.
However, implementing real conditionals is out of scope for this project in my opinion.
If you absolutely need to support multiple OS, I suggest that there is a disptach within the program, you specified in the `hie.yaml`.
Does that make sense? Or is that additional effort in the `ConfigType` worthwhile?

---

BTW, I forgot, the program receives a filepath to load. The command should be able to receive that as well. How should the `shell` API support that?

**Comment by jneira** [comment]
> If you absolutely need to support multiple OS, I suggest that there is a dispatch within the program, you specified in the hie.yaml.

Mmm so `hie-bios` would choose one file or another for each os? looking for a file with the name and a executble extension?
Not sure if that solution will cover some corner cases but it could work

**Comment by fendor** [comment]
> Mmm so hie-bios would choose one file or another for each os? looking for a file with the name and a executble extension?

Not sure how that works, but arent we doing something comparable in HIE?
`hie-cabal-install` exists with and without extension, and the shell picks up the right version? Also, the script could be a Haskell or python script, which would avoid the problem entirely.

**Comment by jneira** [comment]
> `hie-cabal-install` exists with and without extension, and the shell picks up the right file

the shell executes `.bat` and `.cmd` so if we use the shell to execute it may work (findExecutable does not i think)
but if the linux script is `script.sh` (or whateve extension) we would need a `script.sh.bat` 🤔

**Comment by fendor** [comment]
Regarding 
> BTW, I forgot, the program receives a filepath to load. The command should be able to receive that as well. How should the shell API support that?

I have two ideas:
Either we interpolate the string, e.g. 
```yaml
cradle: 
  bios: 
    shell: 'bash -c \"produceFlags $HIE_ARG\" > \"$HIE_BIOS_OUTPUT\""'
```

and replace the string "$HIE_ARG" with the filepath name or we turn "$HIE_ARG" into an environment variable that you can use like in the example above or read in the script.
