### ISSUE TITLE
Cabal cradle matches only exposed-modules to component

### ISSUE THREAD

**Issue by fendor** [mpickering/hie-bios#164]
Upstream issue https://github.com/haskell/cabal/issues/6622

Explanation in hie-bios:

Assume project setup:
```bash
$ cabal init -p example --libandexe --tests --main-is=Main.hs --source-dir=src --application-dir=app --test-dir=test
```

and `hie.yaml`:
```yaml
cradle:
  cabal:
```

then we can observe the following behaviour:
```bash
$ hie-bios flags src/MyLib.hs
Options: [...]
Dependencies: [...]

$ hie-bios flags app/Main.hs
Failed to show flags for "./app/Main.hs": ["Failed to parse result of calling cabal","","cabal.exe: Unknown target './app/Main.hs'.\nThe package example has no file target 'app/Main.hs'.\n\n\n",""]
```

However, the invocation `hie-bios flags app/Main.hs` should work just as well.

**Comment by expipiplus1** [comment]
Adding `Main` to `other-modules` seems to allow hie to work, however it's complained about by hie and probably breaks other tools

```
2020-04-02 14:08:32.123114596 [ThreadId 14] - Warning: Enabling workaround for Main module 'Main' listed in 'other-modules'
2020-04-02 14:08:32.12318556 [ThreadId 14] - illegally!
```

**Comment by expipiplus1** [comment]
I have no idea why, but this configuration allows `src/Main.hs` to work

```yaml
cradle:
  multi:
    - path: "./src"
      config:
        cradle:
          cabal:
    - path: "./src/Main.hs"
      config:
        cradle:
          none:
```
