### ISSUE TITLE
Allow trying multiple entries in a multi cradle if the first one fails

### ISSUE THREAD

**Issue by michaelpj** [mpickering/hie-bios#196]
At the moment, the bare Cabal cradle can't handle components other than the main library component. We can fix this with a multi component where we have a mapping for all the paths to their appropriate components. However, it would be nice to be able to just use this for the components that the bare Cabal cradle *can't* find.

With @fendor 's help, I tried something like this:

```
cradle:
  multi:
    - path: ./.
      config:
        cradle:
          cabal:
    - path: ./.
      config:
        cradle:
          cabal:
            - path: ./mylib/test
              component: mylib:mylib-tests
```

However, it turns out that this will only try the first component that matches a path. So depending which one I put first, either the test component or the library component will work, and the other will give an error.

It would be nice to be able to do something like this.
