### ISSUE TITLE
How should bios cradles run ghc?

### ISSUE THREAD

**Issue by bubba** [mpickering/hie-bios#215]
This a further piece of work from #207:

Cabal and stack cradles can run GHC to get the libdir from `cabal exec ghc -- --print-libdir` and `stack exec ghc -- --print-libdir` respectively.
Direct cradles just use the `ghc` on the path.
But what about bios programs? What ghc are they using exactly? There should be a way for the bios program to report this, either via the program or in a hie.yaml file

**Comment by pepeiborra** [comment]
I was coming around to request this, well spotted @bubba !

A bios cradle:
```
  bios:
    program: "program to run"
    dependency-program: "optional program to run"
    shell: build-tool flags $HIE_BIOS_ARG
    dependency-shell: build-tool dependencies
```
 where each component has the type
```
program, shell :: FilePath -> IO ([Flag], [Target]
dependency_program :: FilePath
dependency_shell :: [FilePath]
```

The path to GHC is not necessarily known statically, so we need a program to compute it, and it should be the same for the entire session - we don't want a different GHC per component or per file!

With that in mind, I propose adding a new optional field to the bios cradle section, which if present is used to compute the ghc path:
```
 with-ghc :: IO String
 with-ghc: "program to run"
```
