### ISSUE TITLE
pattern matching on symlinks use the final path of symlink ?

### ISSUE THREAD

**Issue by teto** [mpickering/hie-bios#218]
hi,

I have this folder with a bunch of folders and only one or 2 relevant to ghcide, e.g:
```
$ ls
_generated/
bazel-bin/ 
...
project/
```
What i would like to do is ignore all folders but "project". Hence I've written the following hie.yaml:
```
# Configuration for hie/ghcide.
# See https://github.com/mpickering/hie-bios/blob/master/README.md for the
# documentation
cradle:
    multi:
        # we default to none because of all the non-haskell folders at the root
        - path: "./"
          config: { cradle: { none:  } }
        - path: "./project"
          config:
              cradle:
                  bios:
                      program: ".hie-bios"
                      dependency-program: ".hie-bios-dependencies"
```

Now if I run `$ hie-bios debug _generated/`, I get the message `Cradle failed to load`. It looks like a real error since I see "No prefixes matched" but I would expec "./" to match ./_generated".
```
hie-bios debug _generated/
Cradle failed to load
Exit Code: ExitSuccess
Stderr: Multi Cradle: No prefixes matched
pwd: /home/teto/nova/jinko2
filepath: /nix/store/llxkyzbl2z06d5ndm2yp2cvl8fyfrxha-jinko-generated-folder
prefixes:
("./",None)
("./project",Bios {prog = ".hie-bios", depsProg = Just ".hie-bios-dependencies"})
```
Now relooking at the error, seems like it compares prefixes against the resolved filepath and because ./_generated is a symlink to /nix/store/llxkyzbl2z06d5ndm2yp2cvl8fyfrxha-jinko-generated-folder, it won't match the prefix. Is that correct ? I would expect to match against the symlink path rather its resolved path.
