### ISSUE TITLE
multicradle: can there be a race issue with HIE_BIOS_OUTPUT ?

### ISSUE THREAD

**Issue by teto** [mpickering/hie-bios#220]
The professional project I am working on is too big to be loaded in ghcide. It has several libraries in a (bazel) monorepo. 
So for now we select one library and generate an appropriate $HIE_BIOS_OUTPUT (follow up on https://github.com/digital-asset/ghcide/issues/679).
I would like to leverage ghcide 0.2 multicradle support and generate a bios file per library. It seems possible with the new "shell" cradle type (note that it doesnt appear in https://github.com/mpickering/hie-bios#configuration-specification).
To sum up I think I should create one cradle per library 
```
cradle:
    multi:
        # we default to none because of all the non-haskell folders at the root
        - path: "./bazel-out"
          config: { cradle: { none:  } }
        - path: "./_generated"
          config: { cradle: { none:  } }
        - path: "./project/scoring"
          config:
              cradle:
                  bios:
                      shell: ".hie-bios scoring $HIE_BIOS_ARG"
                      dependency-program: ".hie-bios-dependencies scoring"
        - path: "./project/maths"
          config:
              cradle:
                  bios:
                      program: ".hie-bios maths $HIE_BIOS_ARG"
                      dependency-program: ".hie-bios-dependencies maths"
        - path: "./project/other"
          config:
              cradle:
                  bios:
                      program: ".hie-bios other $HIE_BIOS_ARG"
                      dependency-program: ".hie-bios-dependencies other"
```

My question is the following:
does `.hie-bios `still has to write to `$HIE_BIOS_OUTPUT` ? Can't there be a race condition where one file erases the other ?

NB: It could be nice to open the github wiki so that people can share some insights.
