### ISSUE TITLE
read flags from file with "direct" cradle

### ISSUE THREAD

**Issue by teto** [mpickering/hie-bios#222]
Right now, I have bazel generate the list of flags. It is too long so I've written a wrapper .hie-bios:
```
cat <<EOF
# long list of flags
....
...
EOF
```
and my hie.yaml
```
        cradle:
            bios:
                program: ".hie-bios-core"
                dependency-program: ".hie-bios-dependencies"
```
I would like to rewrite this a  "direct" cradle but load the arguments from a file instead of putting them in hie.yaml. I think this would be cleaner and remove the overhead of starting a new process. Listing the flags in the hie.yaml would be too long (several cradles with many flags).
