### ISSUE TITLE
bios cradle requires correct ghc in path or in cradle defn

### ISSUE THREAD

**Issue by adamse** [mpickering/hie-bios#253]
We use the bios cradle to hook ghcide up to our build system, that same build system also manages the ghc installation.

It would be preferable if the bios program could tell hie-bios where to look for ghc (or give it the libdir directly) so we don't have to know the path to the compiler outside the buildsystem.

**Comment by fendor** [comment]
What interface do you imagine?
A nice extension *could be* to add a field to the bios cradle:
```
cradle:
  bios:
    program: ./flags.sh
    ghc-program: ./ghc.sh
```
